name: Build SONiC image

on:
  workflow_dispatch:

jobs:
  build-sonic:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install j2cli
        run: |
          sudo apt-get update
          sudo apt-get install python3-pip
          sudo pip3 install j2cli
      - name: Checkout SONiC
        run: ./sonicgit.sh
      - name: Download prebuild dependencies
        run: python3 ./dependencies.py
      - name: Build image
        run: ./build.sh
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: robertvolkmann
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push image
        run: docker push robertvolkmann/ignite-sonic:202205
